using System;
using System.Linq;
using MazeParty.Gameplay;
using MazeParty.Multiplayer;
using Unity.Netcode;
using Unity.Netcode.Components;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;
using Object = UnityEngine.Object;

namespace MazeParty.Editor
{
    /// <summary>
    /// Creates the initial player/lobby presentation assets and performs additive,
    /// one-time migration. Existing authored prefab hierarchies are validated and
    /// are never regenerated by the normal multiplayer rebuild.
    /// </summary>
    public static class MultiplayerPresentationPrefabProjectSetup
    {
        public const string PlayerPresentationPrefabPath =
            "Assets/MazeParty/Prefabs/Multiplayer/PlayerAvatarPresentation.prefab";
        public const string PlayerWorldIndicatorPrefabPath =
            "Assets/MazeParty/Prefabs/Multiplayer/PlayerWorldIndicator.prefab";
        public const string PlayerPresentationAssetsPath =
            "Assets/MazeParty/Resources/MazeParty/Player/PlayerAvatarPresentationAssets.asset";
        public const string PlayerPrefabPath =
            "Assets/MazeParty/Prefabs/Multiplayer/NetworkPlayer.prefab";
        public const string LobbyArenaPrefabPath =
            "Assets/MazeParty/Prefabs/Multiplayer/World/LobbyArena.prefab";
        public const string GrenadeRangeIndicatorPrefabPath =
            "Assets/MazeParty/Prefabs/Board/UI/GrenadeRangeIndicator.prefab";

        private const string BootstrapScenePath =
            "Assets/MazeParty/Scenes/Multiplayer/OnlineBootstrap.unity";
        private const string PlayerAssetFolder =
            "Assets/MazeParty/Prefabs/Multiplayer/Player";
        private const string BodyMaterialPath =
            PlayerAssetFolder + "/PlayerBody.mat";
        private const string FeatureMaterialPath =
            PlayerAssetFolder + "/PlayerFeature.mat";
        private const string HighlightMaterialPath =
            PlayerAssetFolder + "/PlayerHighlight.mat";
        private const string LobbyFloorMaterialPath =
            "Assets/MazeParty/Board/Materials/RoomNormalA.mat";
        private const string LobbyWallMaterialPath =
            "Assets/MazeParty/Board/Materials/RoomNormalB.mat";
        private const string GrenadeRangeIndicatorMaterialPath =
            "Assets/MazeParty/Board/Materials/GrenadeRangeIndicator.mat";
        private const string HostStarSpritePath =
            "Assets/Ignore/Modern UI Pack/Textures/Icon/Common/Star Filled.png";

        [MenuItem("MazeParty/Multiplayer/Install Player And Lobby Prefabs")]
        public static void Install()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                throw new InvalidOperationException(
                    "Player/lobby prefab installation requires Edit Mode.");
            }
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                return;
            }

            LoadOrCreatePlayerPrefab();
            LoadOrCreateLobbyArenaPrefab();
            InstallLobbySceneInstance();
            AssetDatabase.SaveAssets();
            Debug.Log(
                "Authored player presentation, NetworkPlayer, and lobby arena prefabs are ready.");
        }

        [MenuItem("MazeParty/Multiplayer/Install Shared Player World Indicator")]
        public static void InstallSharedPlayerWorldIndicator()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                throw new InvalidOperationException(
                    "Player world indicator installation requires Edit Mode.");
            }

            EnsurePlayerPresentationAssets();
            AssetDatabase.SaveAssets();
            Debug.Log(
                "Authored shared player world indicator prefab is ready.");
        }

        [MenuItem("MazeParty/Multiplayer/Upgrade Shield And Round Highlights")]
        public static void UpgradeShieldAndRoundHighlights()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                throw new InvalidOperationException(
                    "Shield/highlight migration requires Edit Mode.");
            }

            EnsurePlayerPresentationAssets();
            AssetDatabase.SaveAssets();
            Debug.Log(
                "Water Shield protection and round-location highlight bindings are ready.");
        }

        [MenuItem("MazeParty/Multiplayer/Upgrade Hand Emote Rotations")]
        public static void UpgradeHandEmoteRotations()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                throw new InvalidOperationException(
                    "Hand emote rotation migration requires Edit Mode.");
            }

            UpgradePlayerPresentationHandEmoteRotations();
            AssetDatabase.SaveAssets();
            Debug.Log(
                "Hand emote rotation settings are authored on the shared player presentation.");
        }

        internal static GameObject LoadOrCreatePlayerPrefab()
        {
            var presentation = EnsurePlayerPresentationAssets();
            var grenadeRangeIndicator =
                EnsureGrenadeRangeIndicatorPrefab();
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerPrefabPath);
            if (prefab == null)
            {
                if (AssetDatabase.LoadMainAssetAtPath(PlayerPrefabPath) != null)
                {
                    throw new InvalidOperationException(
                        "An incompatible asset exists at " + PlayerPrefabPath + ".");
                }
                var template = CreateNetworkPlayerTemplate(
                    presentation,
                    grenadeRangeIndicator);
                try
                {
                    prefab = PrefabUtility.SaveAsPrefabAsset(
                        template,
                        PlayerPrefabPath);
                }
                finally
                {
                    Object.DestroyImmediate(template);
                }
            }
            else
            {
                MigrateNetworkPlayerPrefab(
                    presentation,
                    grenadeRangeIndicator);
                prefab = AssetDatabase.LoadAssetAtPath<GameObject>(PlayerPrefabPath);
            }

            ValidateNetworkPlayerPrefab(prefab);
            return prefab;
        }

        [MenuItem("MazeParty/Multiplayer/Upgrade Lobby Nameplates")]
        public static void UpgradeLobbyNameplates()
        {
            UpgradePlayerPresentationLobbyNameplate();
            AssetDatabase.SaveAssets();
            Debug.Log(
                "Lobby ready color and host star are authored on the shared player nameplate.");
        }

        internal static GameObject LoadOrCreateLobbyArenaPrefab()
        {
            EnsureFolder("Assets/MazeParty/Prefabs/Multiplayer/World");
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                LobbyArenaPrefabPath);
            if (prefab == null)
            {
                if (AssetDatabase.LoadMainAssetAtPath(LobbyArenaPrefabPath) != null)
                {
                    throw new InvalidOperationException(
                        "An incompatible asset exists at " +
                        LobbyArenaPrefabPath + ".");
                }
                var template = CreateLobbyArenaTemplate();
                try
                {
                    prefab = PrefabUtility.SaveAsPrefabAsset(
                        template,
                        LobbyArenaPrefabPath);
                }
                finally
                {
                    Object.DestroyImmediate(template);
                }
            }

            ValidateLobbyArenaPrefab(prefab);
            return prefab;
        }

        private static PlayerAvatarPresentationBindings
            EnsurePlayerPresentationAssets()
        {
            EnsureFolder(PlayerAssetFolder);
            EnsureFolder("Assets/MazeParty/Resources/MazeParty/Player");

            var waterShield = SharedVfxProjectSetup
                .EnsureWaterShieldPrefab();
            var worldIndicator = EnsurePlayerWorldIndicatorPrefab(
                waterShield);

            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                PlayerPresentationPrefabPath);
            if (prefab == null)
            {
                if (AssetDatabase.LoadMainAssetAtPath(
                        PlayerPresentationPrefabPath) != null)
                {
                    throw new InvalidOperationException(
                        "An incompatible asset exists at " +
                        PlayerPresentationPrefabPath + ".");
                }
                var template = CreatePlayerPresentationTemplate(
                    waterShield);
                try
                {
                    prefab = PrefabUtility.SaveAsPrefabAsset(
                        template,
                        PlayerPresentationPrefabPath);
                }
                finally
                {
                    Object.DestroyImmediate(template);
                }
            }
            else
            {
                RepairPresentationHitZoneScripts();
                UpgradePlayerPresentationLobbyNameplate();
                UpgradePlayerPresentationShieldVfx(waterShield);
                UpgradePlayerPresentationHandEmoteRotations();
                prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                    PlayerPresentationPrefabPath);
            }

            var bindings = prefab != null
                ? prefab.GetComponent<PlayerAvatarPresentationBindings>()
                : null;
            if (bindings == null || !bindings.HasRequiredReferences)
            {
                throw new InvalidOperationException(
                    "PlayerAvatarPresentation.prefab has incomplete bindings. " +
                    "Repair the prefab instead of recreating it.");
            }
            ValidateShieldVfxInstance(bindings.ShieldVfx);
            ValidateHitZone(bindings.BodyHitbox, PlayerHitRegion.Body);
            ValidateHitZone(bindings.HeadHitbox, PlayerHitRegion.Head);
            ValidateHitZone(bindings.LeftHandHitbox, PlayerHitRegion.Hand);
            ValidateHitZone(bindings.RightHandHitbox, PlayerHitRegion.Hand);

            var assets = AssetDatabase.LoadAssetAtPath<
                PlayerAvatarPresentationAssets>(PlayerPresentationAssetsPath);
            if (assets == null)
            {
                assets = ScriptableObject.CreateInstance<
                    PlayerAvatarPresentationAssets>();
                assets.Configure(bindings, worldIndicator);
                AssetDatabase.CreateAsset(assets, PlayerPresentationAssetsPath);
            }
            else if (assets.PresentationPrefab == null ||
                     assets.WorldIndicatorPrefab == null)
            {
                assets.Configure(bindings, worldIndicator);
                EditorUtility.SetDirty(assets);
            }
            if (!assets.HasRequiredReferences)
            {
                throw new InvalidOperationException(
                    "PlayerAvatarPresentationAssets has incomplete references.");
            }
            return bindings;
        }

        private static PlayerWorldIndicator EnsurePlayerWorldIndicatorPrefab(
            GameObject waterShield)
        {
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                PlayerWorldIndicatorPrefabPath);
            if (prefab == null)
            {
                if (AssetDatabase.LoadMainAssetAtPath(
                        PlayerWorldIndicatorPrefabPath) != null)
                {
                    throw new InvalidOperationException(
                        "An incompatible asset exists at " +
                        PlayerWorldIndicatorPrefabPath + ".");
                }

                var template = CreatePlayerWorldIndicatorTemplate(
                    waterShield);
                try
                {
                    prefab = PrefabUtility.SaveAsPrefabAsset(
                        template,
                        PlayerWorldIndicatorPrefabPath);
                }
                finally
                {
                    Object.DestroyImmediate(template);
                }
            }
            else
            {
                UpgradePlayerWorldIndicatorShieldVfx(waterShield);
                prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                    PlayerWorldIndicatorPrefabPath);
            }

            var indicator = prefab != null
                ? prefab.GetComponent<PlayerWorldIndicator>()
                : null;
            if (indicator == null || !indicator.HasRequiredReferences)
            {
                throw new InvalidOperationException(
                    "PlayerWorldIndicator.prefab has incomplete bindings. " +
                    "Repair the prefab instead of recreating it.");
            }
            ValidateShieldVfxInstance(indicator.LocalStartHighlight);

            return indicator;
        }

        private static BoardGrenadeRangeIndicator
            EnsureGrenadeRangeIndicatorPrefab()
        {
            EnsureFolder("Assets/MazeParty/Prefabs/Board/UI");
            EnsureFolder("Assets/MazeParty/Board/Materials");
            var material = EnsureMaterial(
                GrenadeRangeIndicatorMaterialPath,
                new Color(1f, 0.42f, 0.1f),
                0.05f);
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(
                GrenadeRangeIndicatorPrefabPath);
            if (prefab == null)
            {
                if (AssetDatabase.LoadMainAssetAtPath(
                        GrenadeRangeIndicatorPrefabPath) != null)
                {
                    throw new InvalidOperationException(
                        "An incompatible asset exists at " +
                        GrenadeRangeIndicatorPrefabPath + ".");
                }

                var template = CreateGrenadeRangeIndicatorTemplate(material);
                try
                {
                    prefab = PrefabUtility.SaveAsPrefabAsset(
                        template,
                        GrenadeRangeIndicatorPrefabPath);
                }
                finally
                {
                    Object.DestroyImmediate(template);
                }
            }
            var indicator = prefab != null
                ? prefab.GetComponent<BoardGrenadeRangeIndicator>()
                : null;
            if (indicator == null ||
                !indicator.HasRequiredReferences ||
                indicator.IsVisible ||
                prefab.GetComponentsInChildren<Collider>(true).Length != 0 ||
                prefab.GetComponentsInChildren<NetworkObject>(true).Length != 0)
            {
                throw new InvalidOperationException(
                    "GrenadeRangeIndicator.prefab has incomplete authored " +
                    "bindings. Repair the prefab instead of recreating it.");
            }

            return indicator;
        }

        private static GameObject CreateGrenadeRangeIndicatorTemplate(
            Material material)
        {
            const int segmentCount = 64;
            var root = new GameObject(
                "GrenadeRangeIndicator",
                typeof(BoardGrenadeRangeIndicator));
            var ring = new GameObject("Range Ring", typeof(LineRenderer));
            ring.transform.SetParent(root.transform, false);
            // The player root is authored at capsule-center height. Offset the
            // range ring to the standing foot plane, then keep a small lift to
            // prevent z-fighting with the board surface.
            ring.transform.localPosition = new Vector3(0f, -0.94f, 0f);

            var line = ring.GetComponent<LineRenderer>();
            line.useWorldSpace = false;
            line.loop = true;
            line.positionCount = segmentCount;
            line.widthMultiplier = 0.08f;
            line.numCornerVertices = 2;
            line.numCapVertices = 2;
            line.alignment = LineAlignment.View;
            line.textureMode = LineTextureMode.Stretch;
            line.sharedMaterial = material;
            line.shadowCastingMode = ShadowCastingMode.Off;
            line.receiveShadows = false;
            line.lightProbeUsage = LightProbeUsage.Off;
            line.reflectionProbeUsage = ReflectionProbeUsage.Off;
            for (var index = 0; index < segmentCount; index++)
            {
                var radians = index * Mathf.PI * 2f / segmentCount;
                line.SetPosition(
                    index,
                    new Vector3(Mathf.Cos(radians), 0f, Mathf.Sin(radians)));
            }

            root.GetComponent<BoardGrenadeRangeIndicator>().Configure(
                ring,
                ring.transform,
                line);
            ring.SetActive(false);
            return root;
        }

        /// <summary>
        /// Repairs only the four hit-zone components written with a null
        /// MonoScript reference by the original multi-type PlayerHitZones.cs.
        /// Any additional missing script aborts the migration so unrelated
        /// authored data is never removed implicitly.
        /// </summary>
        private static void RepairPresentationHitZoneScripts()
        {
            var root = PrefabUtility.LoadPrefabContents(
                PlayerPresentationPrefabPath);
            try
            {
                var bindings = root.GetComponent<
                    PlayerAvatarPresentationBindings>();
                if (bindings == null)
                {
                    throw new InvalidOperationException(
                        "PlayerAvatarPresentation.prefab has no bindings component.");
                }

                var hitboxObjects = new[]
                {
                    RequireHitboxObject(bindings.BodyHitbox, "BodyHitbox"),
                    RequireHitboxObject(bindings.HeadHitbox, "HeadHitbox"),
                    RequireHitboxObject(bindings.LeftHandHitbox, "LeftHandHitbox"),
                    RequireHitboxObject(bindings.RightHandHitbox, "RightHandHitbox")
                };

                foreach (var child in root.GetComponentsInChildren<Transform>(true))
                {
                    var missingCount = GameObjectUtility
                        .GetMonoBehavioursWithMissingScriptCount(child.gameObject);
                    if (missingCount == 0)
                    {
                        continue;
                    }

                    var hitboxIndex = Array.IndexOf(hitboxObjects, child.gameObject);
                    var hasValidZone = child.GetComponent<PlayerHitZone>() != null;
                    if (hitboxIndex < 0 || missingCount != 1 || hasValidZone)
                    {
                        throw new InvalidOperationException(
                            "Unexpected missing script on '" +
                            GetHierarchyPath(child, root.transform) +
                            "'. The installer will not remove authored components " +
                            "outside the four known hit-zone migration targets.");
                    }
                }

                var changed = false;
                changed |= RepairHitZone(
                    hitboxObjects[0],
                    PlayerHitRegion.Body);
                changed |= RepairHitZone(
                    hitboxObjects[1],
                    PlayerHitRegion.Head);
                changed |= RepairHitZone(
                    hitboxObjects[2],
                    PlayerHitRegion.Hand);
                changed |= RepairHitZone(
                    hitboxObjects[3],
                    PlayerHitRegion.Hand);

                if (changed)
                {
                    PrefabUtility.SaveAsPrefabAsset(
                        root,
                        PlayerPresentationPrefabPath);
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static GameObject RequireHitboxObject(
            Collider collider,
            string expectedName)
        {
            if (collider == null || collider.gameObject.name != expectedName)
            {
                throw new InvalidOperationException(
                    "PlayerAvatarPresentation.prefab is missing the authored '" +
                    expectedName + "' collider binding.");
            }
            return collider.gameObject;
        }

        private static void UpgradePlayerPresentationLobbyNameplate()
        {
            var root = PrefabUtility.LoadPrefabContents(
                PlayerPresentationPrefabPath);
            try
            {
                var bindings = root.GetComponent<
                    PlayerAvatarPresentationBindings>();
                if (bindings == null || bindings.NameplateAnchor == null)
                {
                    throw new InvalidOperationException(
                        "PlayerAvatarPresentation.prefab has no authored nameplate binding.");
                }

                var changed = false;
                var hostIcon = bindings.LobbyHostIcon;
                if (hostIcon == null)
                {
                    var existing = bindings.NameplateAnchor.Find(
                        "Lobby Host Icon");
                    hostIcon = existing != null
                        ? existing.GetComponent<SpriteRenderer>()
                        : null;
                    if (existing != null && hostIcon == null)
                    {
                        throw new InvalidOperationException(
                            "The authored Lobby Host Icon has no SpriteRenderer.");
                    }

                    if (hostIcon == null)
                    {
                        hostIcon = CreateLobbyHostIcon(
                            bindings.NameplateAnchor);
                    }

                    var serializedBindings = new SerializedObject(bindings);
                    serializedBindings.FindProperty("lobbyHostIcon")
                        .objectReferenceValue = hostIcon;
                    var readyColor = serializedBindings.FindProperty(
                        "lobbyReadyNameColor");
                    if (readyColor.colorValue.g <= readyColor.colorValue.r ||
                        readyColor.colorValue.g <= readyColor.colorValue.b)
                    {
                        readyColor.colorValue =
                            new Color32(88, 220, 112, 255);
                    }
                    serializedBindings.ApplyModifiedPropertiesWithoutUndo();
                    changed = true;
                }

                if (hostIcon.transform.parent != bindings.NameplateAnchor)
                {
                    throw new InvalidOperationException(
                        "The lobby host icon must remain directly under NameplateAnchor.");
                }

                var starSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                    HostStarSpritePath);
                if (starSprite == null)
                {
                    throw new InvalidOperationException(
                        "Modern UI host star is missing at " +
                        HostStarSpritePath + ".");
                }
                if (hostIcon.sprite == null)
                {
                    hostIcon.sprite = starSprite;
                    changed = true;
                }
                if (hostIcon.gameObject.activeSelf)
                {
                    hostIcon.gameObject.SetActive(false);
                    changed = true;
                }

                if (changed)
                {
                    PrefabUtility.SaveAsPrefabAsset(
                        root,
                        PlayerPresentationPrefabPath);
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void UpgradePlayerPresentationShieldVfx(
            GameObject waterShield)
        {
            var root = PrefabUtility.LoadPrefabContents(
                PlayerPresentationPrefabPath);
            try
            {
                var bindings = root.GetComponent<
                    PlayerAvatarPresentationBindings>();
                if (bindings == null)
                {
                    throw new InvalidOperationException(
                        "PlayerAvatarPresentation.prefab has no bindings.");
                }

                var changed = false;
                var shieldVfx = bindings.ShieldVfx;
                if (shieldVfx == null)
                {
                    var existing = root.transform.Find("Water Shield VFX");
                    shieldVfx = existing != null
                        ? existing.gameObject
                        : CreateShieldVfx(root.transform, waterShield);
                    var serialized = new SerializedObject(bindings);
                    var property = serialized.FindProperty("shieldVfx");
                    if (property == null)
                    {
                        throw new InvalidOperationException(
                            "PlayerAvatarPresentationBindings has no " +
                            "shield VFX field. Wait for scripts to compile " +
                            "and retry.");
                    }
                    property.objectReferenceValue = shieldVfx;
                    serialized.ApplyModifiedPropertiesWithoutUndo();
                    changed = true;
                }

                ValidateShieldVfxInstance(shieldVfx);
                if (shieldVfx.activeSelf)
                {
                    shieldVfx.SetActive(false);
                    changed = true;
                }

                if (changed)
                {
                    PrefabUtility.SaveAsPrefabAsset(
                        root,
                        PlayerPresentationPrefabPath);
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void UpgradePlayerPresentationHandEmoteRotations()
        {
            var root = PrefabUtility.LoadPrefabContents(
                PlayerPresentationPrefabPath);
            try
            {
                var bindings = root.GetComponent<
                    PlayerAvatarPresentationBindings>();
                if (bindings == null)
                {
                    throw new InvalidOperationException(
                        "PlayerAvatarPresentation.prefab has no bindings.");
                }

                if (!bindings.EnsureHandEmoteRotationSettings())
                {
                    return;
                }
                EditorUtility.SetDirty(bindings);
                PrefabUtility.SaveAsPrefabAsset(
                    root,
                    PlayerPresentationPrefabPath);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void UpgradePlayerWorldIndicatorShieldVfx(
            GameObject waterShield)
        {
            var root = PrefabUtility.LoadPrefabContents(
                PlayerWorldIndicatorPrefabPath);
            try
            {
                var indicator = root.GetComponent<PlayerWorldIndicator>();
                if (indicator == null)
                {
                    throw new InvalidOperationException(
                        "PlayerWorldIndicator.prefab has no bindings.");
                }

                var changed = false;
                var previousHighlight = indicator.LocalStartHighlight;
                var shieldVfx = previousHighlight;
                if (!IsShieldVfxInstance(shieldVfx))
                {
                    var existing = root.transform.Find("Water Shield VFX");
                    shieldVfx = existing != null &&
                                IsShieldVfxInstance(existing.gameObject)
                        ? existing.gameObject
                        : CreateShieldVfx(root.transform, waterShield);

                    var serialized = new SerializedObject(indicator);
                    var property = serialized.FindProperty(
                        "localStartHighlight");
                    if (property == null)
                    {
                        throw new InvalidOperationException(
                            "PlayerWorldIndicator has no local location " +
                            "highlight field. Wait for scripts to compile " +
                            "and retry.");
                    }
                    property.objectReferenceValue = shieldVfx;
                    serialized.ApplyModifiedPropertiesWithoutUndo();
                    if (previousHighlight != null &&
                        previousHighlight != shieldVfx &&
                        previousHighlight.name ==
                            "Local Player Start Highlight")
                    {
                        Object.DestroyImmediate(previousHighlight);
                    }
                    changed = true;
                }

                ValidateShieldVfxInstance(shieldVfx);
                if (shieldVfx.activeSelf)
                {
                    shieldVfx.SetActive(false);
                    changed = true;
                }

                if (changed)
                {
                    PrefabUtility.SaveAsPrefabAsset(
                        root,
                        PlayerWorldIndicatorPrefabPath);
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static SpriteRenderer CreateLobbyHostIcon(Transform nameplate)
        {
            var starSprite = AssetDatabase.LoadAssetAtPath<Sprite>(
                HostStarSpritePath);
            if (starSprite == null)
            {
                throw new InvalidOperationException(
                    "Modern UI host star is missing at " +
                    HostStarSpritePath + ".");
            }

            var iconObject = new GameObject(
                "Lobby Host Icon",
                typeof(SpriteRenderer));
            iconObject.transform.SetParent(nameplate, false);
            iconObject.transform.localPosition = new Vector3(-0.95f, 0f, 0f);
            iconObject.transform.localScale = Vector3.one * 0.28f;
            var hostIcon = iconObject.GetComponent<SpriteRenderer>();
            hostIcon.sprite = starSprite;
            hostIcon.color = new Color32(255, 214, 86, 255);
            hostIcon.sortingOrder = 1;
            hostIcon.shadowCastingMode = ShadowCastingMode.Off;
            hostIcon.receiveShadows = false;
            iconObject.SetActive(false);
            return hostIcon;
        }

        private static bool RepairHitZone(
            GameObject hitbox,
            PlayerHitRegion expectedRegion)
        {
            var missingCount = GameObjectUtility
                .GetMonoBehavioursWithMissingScriptCount(hitbox);
            var zone = hitbox.GetComponent<PlayerHitZone>();
            if (missingCount == 0)
            {
                if (zone == null)
                {
                    throw new InvalidOperationException(
                        "Authored hitbox '" + hitbox.name +
                        "' has no PlayerHitZone component.");
                }
                if (zone.Region == expectedRegion)
                {
                    return false;
                }

                zone.Configure(expectedRegion);
                EditorUtility.SetDirty(zone);
                return true;
            }

            if (missingCount != 1 || zone != null)
            {
                throw new InvalidOperationException(
                    "Authored hitbox '" + hitbox.name +
                    "' has an unexpected missing-script layout.");
            }

            GameObjectUtility.RemoveMonoBehavioursWithMissingScript(hitbox);
            hitbox.AddComponent<PlayerHitZone>().Configure(expectedRegion);
            return true;
        }

        private static void ValidateHitZone(
            Collider collider,
            PlayerHitRegion expectedRegion)
        {
            var zone = collider != null
                ? collider.GetComponent<PlayerHitZone>()
                : null;
            if (zone == null || zone.Region != expectedRegion ||
                GameObjectUtility.GetMonoBehavioursWithMissingScriptCount(
                    collider.gameObject) != 0)
            {
                throw new InvalidOperationException(
                    "PlayerAvatarPresentation.prefab has an incomplete '" +
                    (collider != null ? collider.gameObject.name : "hitbox") +
                    "' hit-zone contract.");
            }
        }

        private static string GetHierarchyPath(
            Transform target,
            Transform root)
        {
            var path = target.name;
            while (target.parent != null && target.parent != root.parent)
            {
                target = target.parent;
                path = target.name + "/" + path;
            }
            return path;
        }

        private static GameObject CreatePlayerPresentationTemplate(
            GameObject waterShield)
        {
            var bodyMaterial = EnsureMaterial(
                BodyMaterialPath,
                new Color(0.95f, 0.25f, 0.25f),
                0.22f);
            var featureMaterial = EnsureMaterial(
                FeatureMaterialPath,
                new Color(0.025f, 0.02f, 0.02f),
                0.12f);
            var highlightMaterial = EnsureMaterial(
                HighlightMaterialPath,
                Color.white,
                0.05f);

            var root = new GameObject(
                "VisualRoot",
                typeof(PlayerAvatarPresentationBindings));
            var world = CreateAnchor(root.transform, "WorldModel");
            var body = CreatePosePart(
                world,
                "BodyAnchor",
                PrimitiveType.Capsule,
                bodyMaterial,
                out var bodyRenderer);
            var head = CreatePosePart(
                world,
                "HeadAnchor",
                PrimitiveType.Sphere,
                bodyMaterial,
                out var headRenderer);
            var leftHand = CreatePosePart(
                world,
                "LeftHandAnchor",
                PrimitiveType.Sphere,
                bodyMaterial,
                out var leftHandRenderer);
            var rightHand = CreatePosePart(
                world,
                "RightHandAnchor",
                PrimitiveType.Sphere,
                bodyMaterial,
                out var rightHandRenderer);
            var leftEye = CreatePosePart(
                world,
                "LeftEyeAnchor",
                PrimitiveType.Sphere,
                featureMaterial,
                out _);
            var rightEye = CreatePosePart(
                world,
                "RightEyeAnchor",
                PrimitiveType.Sphere,
                featureMaterial,
                out _);
            var mouth = CreatePosePart(
                world,
                "MouthAnchor",
                PrimitiveType.Sphere,
                featureMaterial,
                out _);

            var hat = CreateAnchor(world, "HatAnchor");
            var outfit = CreateAnchor(world, "OutfitAnchor");
            var worldItems = CreateAnchor(world, "ItemUseAnchor");
            worldItems.localScale = Vector3.one * 0.72f;
            var worldGestures = CreateAnchor(world, "Gesture Hands");

            var faceObject = new GameObject(
                "Face Sprite",
                typeof(SpriteRenderer));
            faceObject.transform.SetParent(head, false);
            faceObject.transform.localPosition = new Vector3(0f, 0f, 0.51f);
            faceObject.transform.localScale = Vector3.one * 0.15625f;
            var face = faceObject.GetComponent<SpriteRenderer>();
            face.shadowCastingMode = ShadowCastingMode.Off;
            face.receiveShadows = false;

            var nameplate = CreateAnchor(root.transform, "NameplateAnchor");
            var nameObject = new GameObject("PlayerName", typeof(TextMesh));
            nameObject.transform.SetParent(nameplate, false);
            var nameText = nameObject.GetComponent<TextMesh>();
            nameText.text = "PLAYER";
            nameText.anchor = TextAnchor.MiddleCenter;
            nameText.alignment = TextAlignment.Center;
            nameText.fontSize = 64;
            nameText.characterSize = 0.025f;
            nameText.color = Color.white;
            var font = Resources.Load<Font>("MazeParty/Fonts/PlayerNameFont") ??
                       Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            if (font != null)
            {
                nameText.font = font;
            }
            WorldTextOcclusion.Apply(nameText);

            var hostIcon = CreateLobbyHostIcon(nameplate);

            var hitboxRoot = CreateAnchor(root.transform, "HitboxRoot");
            var bodyHitbox = CreateHitbox<CapsuleCollider>(
                hitboxRoot,
                "BodyHitbox",
                PlayerHitRegion.Body);
            bodyHitbox.radius = 0.36f;
            var headHitbox = CreateHitbox<SphereCollider>(
                hitboxRoot,
                "HeadHitbox",
                PlayerHitRegion.Head);
            headHitbox.radius = 0.38f;
            var leftHandHitbox = CreateHitbox<SphereCollider>(
                hitboxRoot,
                "LeftHandHitbox",
                PlayerHitRegion.Hand);
            leftHandHitbox.radius = 0.16f;
            var rightHandHitbox = CreateHitbox<SphereCollider>(
                hitboxRoot,
                "RightHandHitbox",
                PlayerHitRegion.Hand);
            rightHandHitbox.radius = 0.16f;

            var firstPersonRoot = CreateAnchor(
                root.transform,
                "FirstPersonPresentation");
            var firstPersonHands = CreateAnchor(
                firstPersonRoot,
                "FirstPersonHands");
            var firstPersonLeft = CreatePosePart(
                firstPersonHands,
                "FirstPersonLeftHand",
                PrimitiveType.Sphere,
                bodyMaterial,
                out var firstPersonLeftRenderer);
            var firstPersonRight = CreatePosePart(
                firstPersonHands,
                "FirstPersonRightHand",
                PrimitiveType.Sphere,
                bodyMaterial,
                out var firstPersonRightRenderer);
            firstPersonLeft.localPosition = new Vector3(-0.27f, -0.24f, 0.52f);
            firstPersonRight.localPosition = new Vector3(0.27f, -0.24f, 0.52f);
            firstPersonLeft.localScale = Vector3.one * 0.22f;
            firstPersonRight.localScale = Vector3.one * 0.22f;
            var firstPersonItems = CreateAnchor(
                firstPersonRoot,
                "FirstPersonItemUseAnchor");
            firstPersonItems.localScale = Vector3.one * 0.78f;
            var firstPersonGestures = CreateAnchor(
                firstPersonRoot,
                "First Person Gesture Hands");
            firstPersonGestures.localPosition = new Vector3(0f, -0.22f, 0.65f);
            firstPersonGestures.localScale = Vector3.one * 0.55f;
            firstPersonGestures.localRotation = Quaternion.Euler(0f, 180f, 0f);

            var highlight = CreateHighlight(
                root.transform,
                highlightMaterial);
            var shieldVfx = CreateShieldVfx(
                root.transform,
                waterShield);

            root.GetComponent<PlayerAvatarPresentationBindings>().Configure(
                world,
                body,
                head,
                leftHand,
                rightHand,
                leftEye,
                rightEye,
                mouth,
                hat,
                outfit,
                worldItems,
                worldGestures,
                face,
                nameplate,
                nameText,
                hostIcon,
                highlight,
                shieldVfx,
                firstPersonRoot,
                firstPersonHands,
                firstPersonLeft,
                firstPersonRight,
                firstPersonItems,
                firstPersonGestures,
                bodyHitbox,
                headHitbox,
                leftHandHitbox,
                rightHandHitbox,
                new[]
                {
                    bodyRenderer,
                    headRenderer,
                    leftHandRenderer,
                    rightHandRenderer,
                    firstPersonLeftRenderer,
                    firstPersonRightRenderer
                });
            highlight.SetActive(false);
            shieldVfx.SetActive(false);
            return root;
        }

        private static GameObject CreatePlayerWorldIndicatorTemplate(
            GameObject waterShield)
        {
            var root = new GameObject(
                "Player World Indicator",
                typeof(PlayerWorldIndicator));
            var nameplate = CreateAnchor(root.transform, "NameplateAnchor");
            var nameObject = new GameObject("PlayerName", typeof(TextMesh));
            nameObject.transform.SetParent(nameplate, false);
            var nameText = nameObject.GetComponent<TextMesh>();
            nameText.text = "PLAYER";
            nameText.anchor = TextAnchor.MiddleCenter;
            nameText.alignment = TextAlignment.Center;
            nameText.fontSize = 64;
            nameText.characterSize = 0.025f;
            nameText.color = Color.white;
            var font = Resources.Load<Font>(
                           "MazeParty/Fonts/PlayerNameFont") ??
                       Resources.GetBuiltinResource<Font>(
                           "LegacyRuntime.ttf");
            if (font != null)
            {
                nameText.font = font;
            }
            WorldTextOcclusion.Apply(nameText);

            var highlight = CreateShieldVfx(
                root.transform,
                waterShield);
            highlight.SetActive(false);
            root.GetComponent<PlayerWorldIndicator>().Configure(
                nameplate,
                nameText,
                highlight);
            return root;
        }

        private static void MigrateNetworkPlayerPrefab(
            PlayerAvatarPresentationBindings presentationPrefab,
            BoardGrenadeRangeIndicator grenadeRangeIndicatorPrefab)
        {
            var root = PrefabUtility.LoadPrefabContents(PlayerPrefabPath);
            try
            {
                var changed = false;
                var visual = root.GetComponent<PlayerAvatarVisual>();
                var networkAvatar = root.GetComponent<NetworkPlayerAvatar>();
                if (visual == null || networkAvatar == null)
                {
                    throw new InvalidOperationException(
                        "NetworkPlayer.prefab is missing required runtime components.");
                }

                var controller = root.GetComponent<CharacterController>();
                if (controller == null)
                {
                    throw new InvalidOperationException(
                        "NetworkPlayer.prefab is missing its root CharacterController.");
                }
                if (!Mathf.Approximately(
                        controller.radius,
                        PlayerAvatarVisual.MovementControllerRadius))
                {
                    controller.radius =
                        PlayerAvatarVisual.MovementControllerRadius;
                    changed = true;
                }

                var bindings = root.GetComponentInChildren<
                    PlayerAvatarPresentationBindings>(true);
                if (bindings == null)
                {
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                        presentationPrefab.gameObject,
                        root.transform);
                    instance.name = presentationPrefab.gameObject.name;
                    bindings = instance.GetComponent<
                        PlayerAvatarPresentationBindings>();
                    changed = true;
                }
                if (visual.Bindings != bindings)
                {
                    visual.ConfigurePresentationBindings(bindings);
                    changed = true;
                }

                var grenadeRangeIndicator = root.GetComponentInChildren<
                    BoardGrenadeRangeIndicator>(true);
                if (grenadeRangeIndicator == null)
                {
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                        grenadeRangeIndicatorPrefab.gameObject,
                        root.transform);
                    instance.name =
                        grenadeRangeIndicatorPrefab.gameObject.name;
                    grenadeRangeIndicator = instance.GetComponent<
                        BoardGrenadeRangeIndicator>();
                    changed = true;
                }

                var eyePivot = root.transform.Find("CameraPivot");
                if (eyePivot == null)
                {
                    eyePivot = new GameObject("CameraPivot").transform;
                    eyePivot.SetParent(root.transform, false);
                    eyePivot.localPosition = new Vector3(0f, 0.75f, 0f);
                    changed = true;
                }
                var avatarObject = new SerializedObject(networkAvatar);
                var eyeProperty = avatarObject.FindProperty("eyePivot");
                if (eyeProperty.objectReferenceValue != eyePivot)
                {
                    eyeProperty.objectReferenceValue = eyePivot;
                    changed = true;
                }
                var grenadeRangeProperty = avatarObject.FindProperty(
                    "grenadeRangeIndicator");
                if (grenadeRangeProperty == null)
                {
                    throw new InvalidOperationException(
                        "NetworkPlayerAvatar is missing the serialized " +
                        "grenade range indicator binding.");
                }
                if (grenadeRangeProperty.objectReferenceValue !=
                    grenadeRangeIndicator)
                {
                    grenadeRangeProperty.objectReferenceValue =
                        grenadeRangeIndicator;
                    changed = true;
                }
                avatarObject.ApplyModifiedPropertiesWithoutUndo();
                if (root.GetComponent<PlayerHitZoneOwner>() == null)
                {
                    root.AddComponent<PlayerHitZoneOwner>();
                    changed = true;
                }

                if (changed)
                {
                    PrefabUtility.SaveAsPrefabAsset(root, PlayerPrefabPath);
                }
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static GameObject CreateNetworkPlayerTemplate(
            PlayerAvatarPresentationBindings presentationPrefab,
            BoardGrenadeRangeIndicator grenadeRangeIndicatorPrefab)
        {
            var root = new GameObject("NetworkPlayer");
            var controller = root.AddComponent<CharacterController>();
            controller.height = 2f;
            controller.radius = PlayerAvatarVisual.MovementControllerRadius;
            controller.center = Vector3.zero;
            root.AddComponent<NetworkObject>();
            var networkTransform = root.AddComponent<NetworkTransform>();
            networkTransform.Interpolate = true;
            networkTransform.SyncScaleX = false;
            networkTransform.SyncScaleY = false;
            networkTransform.SyncScaleZ = false;

            var presentation = (GameObject)PrefabUtility.InstantiatePrefab(
                presentationPrefab.gameObject,
                root.transform);
            presentation.name = presentationPrefab.gameObject.name;
            var visual = root.AddComponent<PlayerAvatarVisual>();
            visual.ConfigurePresentationBindings(
                presentation.GetComponent<PlayerAvatarPresentationBindings>());
            root.AddComponent<PlayerHitZoneOwner>();
            var eyePivot = new GameObject("CameraPivot").transform;
            eyePivot.SetParent(root.transform, false);
            eyePivot.localPosition = new Vector3(0f, 0.75f, 0f);
            var networkAvatar = root.AddComponent<NetworkPlayerAvatar>();
            var grenadeRangeInstance =
                (GameObject)PrefabUtility.InstantiatePrefab(
                    grenadeRangeIndicatorPrefab.gameObject,
                    root.transform);
            grenadeRangeInstance.name =
                grenadeRangeIndicatorPrefab.gameObject.name;
            var grenadeRangeIndicator = grenadeRangeInstance.GetComponent<
                BoardGrenadeRangeIndicator>();
            var avatarObject = new SerializedObject(networkAvatar);
            avatarObject.FindProperty("eyePivot").objectReferenceValue = eyePivot;
            avatarObject.FindProperty("grenadeRangeIndicator")
                .objectReferenceValue = grenadeRangeIndicator;
            avatarObject.ApplyModifiedPropertiesWithoutUndo();
            var walls = root.AddComponent<PlayerBoardBoundaryWalls>();
            walls.ConfigureWorldPrefabs(BoardWorldPrefabProjectSetup.EnsureAssets());
            return root;
        }

        private static GameObject CreateLobbyArenaTemplate()
        {
            var floorMaterial = LoadRequiredMaterial(LobbyFloorMaterialPath);
            var wallMaterial = LoadRequiredMaterial(LobbyWallMaterialPath);
            var root = new GameObject(
                "LobbyArena",
                typeof(LobbyArena),
                typeof(LobbyArenaBindings));
            var presentation = new GameObject("Presentation");
            presentation.transform.SetParent(root.transform, false);
            CreateLobbyPart(
                "Floor",
                presentation.transform,
                new Vector3(0f, -0.25f, 0f),
                new Vector3(13f, 0.5f, 9f),
                floorMaterial);
            CreateLobbyPart(
                "North Wall",
                presentation.transform,
                new Vector3(0f, 0.4f, 4.25f),
                new Vector3(13f, 0.8f, 0.5f),
                wallMaterial);
            CreateLobbyPart(
                "South Wall",
                presentation.transform,
                new Vector3(0f, 0.4f, -4.25f),
                new Vector3(13f, 0.8f, 0.5f),
                wallMaterial);
            CreateLobbyPart(
                "East Wall",
                presentation.transform,
                new Vector3(6.25f, 0.4f, 0f),
                new Vector3(0.5f, 0.8f, 8f),
                wallMaterial);
            CreateLobbyPart(
                "West Wall",
                presentation.transform,
                new Vector3(-6.25f, 0.4f, 0f),
                new Vector3(0.5f, 0.8f, 8f),
                wallMaterial);

            var boundsObject = new GameObject(
                "Horizontal Bounds",
                typeof(BoxCollider));
            boundsObject.transform.SetParent(root.transform, false);
            var bounds = boundsObject.GetComponent<BoxCollider>();
            bounds.size = new Vector3(12f, 2f, 8f);
            bounds.enabled = false;

            var spawnRoot = new GameObject("Spawn Anchors").transform;
            spawnRoot.SetParent(root.transform, false);
            var positions = new[]
            {
                new Vector3(-2.7f, 1f, -1.8f),
                new Vector3(2.7f, 1f, -1.8f),
                new Vector3(-2.7f, 1f, 1.8f),
                new Vector3(2.7f, 1f, 1.8f)
            };
            var spawns = new Transform[positions.Length];
            for (var index = 0; index < positions.Length; index++)
            {
                spawns[index] = CreateAnchor(
                    spawnRoot,
                    "Player Spawn " + (index + 1));
                spawns[index].localPosition = positions[index];
            }

            var bindings = root.GetComponent<LobbyArenaBindings>();
            bindings.Configure(presentation, bounds, spawns);
            root.GetComponent<LobbyArena>().ConfigureBindings(bindings);
            return root;
        }

        private static void InstallLobbySceneInstance()
        {
            var prefab = LoadOrCreateLobbyArenaPrefab();
            var scene = EditorSceneManager.OpenScene(
                BootstrapScenePath,
                OpenSceneMode.Single);
            var arenas = scene.GetRootGameObjects()
                .SelectMany(root =>
                    root.GetComponentsInChildren<LobbyArena>(true))
                .ToArray();
            if (arenas.Length > 1)
            {
                throw new InvalidOperationException(
                    "OnlineBootstrap contains multiple LobbyArena instances.");
            }
            if (arenas.Length == 1 &&
                PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(
                    arenas[0].gameObject) == LobbyArenaPrefabPath &&
                arenas[0].HasRequiredReferences)
            {
                return;
            }

            var position = arenas.Length == 1
                ? arenas[0].RoomCenter
                : new Vector3(3.5f, 0f, 0f);
            if (arenas.Length == 1)
            {
                Object.DestroyImmediate(arenas[0].gameObject);
            }
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(
                prefab,
                scene);
            instance.transform.position = position;
            EditorSceneManager.MarkSceneDirty(scene);
            EditorSceneManager.SaveScene(scene);
        }

        private static void ValidateNetworkPlayerPrefab(GameObject prefab)
        {
            var visual = prefab != null
                ? prefab.GetComponent<PlayerAvatarVisual>()
                : null;
            var avatar = prefab != null
                ? prefab.GetComponent<NetworkPlayerAvatar>()
                : null;
            var grenadeRangeIndicators = prefab != null
                ? prefab.GetComponentsInChildren<
                    BoardGrenadeRangeIndicator>(true)
                : Array.Empty<BoardGrenadeRangeIndicator>();
            var grenadeRangeIndicator = grenadeRangeIndicators.Length == 1
                ? grenadeRangeIndicators[0]
                : null;
            var avatarObject = avatar != null
                ? new SerializedObject(avatar)
                : null;
            var grenadeRangeProperty = avatarObject?.FindProperty(
                "grenadeRangeIndicator");
            var controller = prefab != null
                ? prefab.GetComponent<CharacterController>()
                : null;
            var movementControllers = prefab != null
                ? prefab.GetComponentsInChildren<CharacterController>(true)
                : Array.Empty<CharacterController>();
            var nonMovementColliders = prefab != null
                ? prefab.GetComponentsInChildren<Collider>(true)
                    .Where(collider => collider != controller)
                    .ToArray()
                : Array.Empty<Collider>();
            if (prefab == null ||
                prefab.GetComponent<NetworkObject>() == null ||
                prefab.GetComponent<NetworkTransform>() == null ||
                controller == null ||
                movementControllers.Length != 1 ||
                movementControllers[0] != controller ||
                !controller.enabled ||
                !Mathf.Approximately(
                    controller.radius,
                    PlayerAvatarVisual.MovementControllerRadius) ||
                nonMovementColliders.Length != 4 ||
                nonMovementColliders.Any(collider =>
                    !collider.isTrigger ||
                    collider.GetComponent<PlayerHitZone>() == null) ||
                prefab.GetComponent<PlayerHitZoneOwner>() == null ||
                prefab.GetComponent<PlayerBoardBoundaryWalls>() == null ||
                visual == null || visual.Bindings == null ||
                !visual.Bindings.HasRequiredReferences ||
                avatar == null || prefab.transform.Find("CameraPivot") == null ||
                grenadeRangeIndicator == null ||
                !grenadeRangeIndicator.HasRequiredReferences ||
                grenadeRangeIndicator.IsVisible ||
                grenadeRangeIndicator.GetComponentsInChildren<Collider>(true)
                    .Length != 0 ||
                grenadeRangeIndicator.GetComponentsInChildren<NetworkObject>(true)
                    .Length != 0 ||
                PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(
                    grenadeRangeIndicator.gameObject) !=
                    GrenadeRangeIndicatorPrefabPath ||
                grenadeRangeProperty == null ||
                grenadeRangeProperty.objectReferenceValue !=
                    grenadeRangeIndicator)
            {
                throw new InvalidOperationException(
                    "NetworkPlayer.prefab has incomplete authored contracts.");
            }
        }

        private static void ValidateLobbyArenaPrefab(GameObject prefab)
        {
            var arena = prefab != null ? prefab.GetComponent<LobbyArena>() : null;
            if (arena == null || !arena.HasRequiredReferences ||
                arena.SpawnCount != MultiplayerConstants.MaxPlayers)
            {
                throw new InvalidOperationException(
                    "LobbyArena.prefab has incomplete authored bindings.");
            }
        }

        private static Material EnsureMaterial(
            string path,
            Color color,
            float smoothness)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (material != null)
            {
                return material;
            }
            material = WorldTextOcclusion.CreateBuildSafeLitMaterial(
                System.IO.Path.GetFileNameWithoutExtension(path));
            if (material == null)
            {
                throw new InvalidOperationException(
                    "A build-safe Lit shader is required for player presentation.");
            }
            material.SetColor("_BaseColor", color);
            material.SetColor("_Color", color);
            material.SetFloat("_Metallic", 0f);
            material.SetFloat("_Smoothness", smoothness);
            AssetDatabase.CreateAsset(material, path);
            return material;
        }

        private static Material LoadRequiredMaterial(string path)
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(path);
            if (material == null)
            {
                throw new InvalidOperationException(
                    "Required material is missing: " + path);
            }
            return material;
        }

        private static Transform CreateAnchor(Transform parent, string name)
        {
            var anchor = new GameObject(name).transform;
            anchor.SetParent(parent, false);
            return anchor;
        }

        private static Transform CreatePosePart(
            Transform parent,
            string name,
            PrimitiveType primitive,
            Material material,
            out Renderer renderer)
        {
            var anchor = CreateAnchor(parent, name);
            var visual = CreatePrimitive(
                name + " Visual",
                primitive,
                anchor,
                material);
            renderer = visual.GetComponent<Renderer>();
            return anchor;
        }

        private static GameObject CreatePrimitive(
            string name,
            PrimitiveType primitive,
            Transform parent,
            Material material)
        {
            var value = GameObject.CreatePrimitive(primitive);
            value.name = name;
            value.transform.SetParent(parent, false);
            var collider = value.GetComponent<Collider>();
            if (collider != null)
            {
                Object.DestroyImmediate(collider);
            }
            var renderer = value.GetComponent<Renderer>();
            renderer.sharedMaterial = material;
            return value;
        }

        private static T CreateHitbox<T>(
            Transform parent,
            string name,
            PlayerHitRegion region)
            where T : Collider
        {
            var value = new GameObject(name);
            value.transform.SetParent(parent, false);
            value.AddComponent<PlayerHitZone>().Configure(region);
            var collider = value.AddComponent<T>();
            collider.isTrigger = true;
            return collider;
        }

        private static GameObject CreateShieldVfx(
            Transform parent,
            GameObject waterShield)
        {
            if (waterShield == null)
            {
                throw new InvalidOperationException(
                    "The shared Water Shield wrapper is required.");
            }

            var instance = PrefabUtility.InstantiatePrefab(
                waterShield,
                parent) as GameObject;
            if (instance == null)
            {
                throw new InvalidOperationException(
                    "Could not instantiate the shared Water Shield wrapper.");
            }

            instance.name = "Water Shield VFX";
            instance.transform.localPosition = Vector3.zero;
            instance.transform.localRotation = Quaternion.identity;
            instance.transform.localScale = Vector3.one;
            instance.SetActive(false);
            return instance;
        }

        private static bool IsShieldVfxInstance(GameObject candidate)
        {
            return candidate != null && string.Equals(
                PrefabUtility.GetPrefabAssetPathOfNearestInstanceRoot(
                    candidate),
                SharedVfxProjectSetup.WaterShieldPrefabPath,
                StringComparison.OrdinalIgnoreCase);
        }

        private static void ValidateShieldVfxInstance(GameObject candidate)
        {
            if (!IsShieldVfxInstance(candidate) ||
                candidate.GetComponentsInChildren<Collider>(true).Length > 0 ||
                candidate.GetComponentsInChildren<NetworkObject>(true).Length > 0)
            {
                throw new InvalidOperationException(
                    "Player presentation shield must use the shared, " +
                    "presentation-only WaterShield.prefab wrapper.");
            }
        }

        private static GameObject CreateHighlight(
            Transform parent,
            Material material)
        {
            var root = new GameObject("Local Player Top View Highlight");
            root.transform.SetParent(parent, false);
            root.transform.localPosition = new Vector3(0f, -0.98f, 0f);
            const float extent = 0.72f;
            const float width = 0.09f;
            CreateHighlightLine(
                root.transform,
                "North",
                new Vector3(0f, 0f, extent),
                new Vector3(extent * 2f + width, 0.025f, width),
                material);
            CreateHighlightLine(
                root.transform,
                "South",
                new Vector3(0f, 0f, -extent),
                new Vector3(extent * 2f + width, 0.025f, width),
                material);
            CreateHighlightLine(
                root.transform,
                "East",
                new Vector3(extent, 0f, 0f),
                new Vector3(width, 0.025f, extent * 2f + width),
                material);
            CreateHighlightLine(
                root.transform,
                "West",
                new Vector3(-extent, 0f, 0f),
                new Vector3(width, 0.025f, extent * 2f + width),
                material);
            return root;
        }

        private static void CreateHighlightLine(
            Transform parent,
            string name,
            Vector3 position,
            Vector3 scale,
            Material material)
        {
            var line = CreatePrimitive(
                name,
                PrimitiveType.Cube,
                parent,
                material);
            line.transform.localPosition = position;
            line.transform.localScale = scale;
            var renderer = line.GetComponent<Renderer>();
            renderer.shadowCastingMode = ShadowCastingMode.Off;
            renderer.receiveShadows = false;
        }

        private static void CreateLobbyPart(
            string name,
            Transform parent,
            Vector3 position,
            Vector3 scale,
            Material material)
        {
            var value = GameObject.CreatePrimitive(PrimitiveType.Cube);
            value.name = name;
            value.transform.SetParent(parent, false);
            value.transform.localPosition = position;
            value.transform.localScale = scale;
            value.GetComponent<Renderer>().sharedMaterial = material;
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path))
            {
                return;
            }
            var slash = path.LastIndexOf('/');
            var parent = path.Substring(0, slash);
            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, path.Substring(slash + 1));
        }
    }
}
